[project]
name = "pathlabapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vikas kesharvani", email = "vikashkesharvani62@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.4.3",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.6",
    "langchain-openai>=1.6.7",
    "langgraph>=1.2.12",
    "langgraph-cli[inmem]>=0.4.32",
    "pymupdf>=1.28.2",
    "python-dotenv>=1.2.4",
]

[project.scripts]
pathlabapp = "pathlabapp:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
